### ISSUE TITLE
Open-in FF (for Chrome) doesn't work for links in Gmail

### ISSUE THREAD

**Issue by e-t-l** [andy-portmen/open-in#33] opened 2019-08-27 17:43 UTC
I use Firefox for everything except Gmail, because Chrome has some mail-managing extensions that FF doesn't. As a result, I'd like to be able to click a link in my email and have it open in FF. I've already enabled "Open with Keyboard-Mouse-Click Combinations" and unchecked all boxes but left the drop-down menu on "Left click" (essentially making Open-in FF the default action for any left-click). I have confirmed this works on other websites; however it doesn't work for links in Gmail emails for some reason. It _does_ still work for links within the gmail website, but outside of the body of the emails themselves. Can this be fixed?

**Comment by markstos** [comment] 2020-02-03 02:42
This seems like a dupe of #34 No mention is made of trying "Reverse Mode" which sounds like exactly what's needed here. 

I recommend closing this issue in favor of #34 (which should also possibly be closed as being addressed by Reverse Mode).

**Comment by e-t-l** [comment] 2020-02-09 21:10
Not a duplicate. I haven't heard of "Reverse Mode," which I'll look into for the purposes of blacklisting certain domains as described in #34. The issue in this thread is separate - it's that Open-in FF simply does not work for links in the body of Gmail messages. I suspect it may have to do with Gmail employing a great deal of javascript in the email viewing pane, to the extent that links function less like normal hyperlinks and more like JS objects that Open-in FF isn't currently equipped to deal with.

**Comment by markstos** [comment] 2020-02-10 12:23
Ah. I think it's because Google has rewritten the links to point to a
Google domain. That way Google can track the clicks.

**Comment by andy-portmen** [comment] 2020-02-12 07:44
> Open-in FF simply does not work for links in the body of Gmail messages.

@e-t-l I just tested with Chrome and it works for me. Do you have the issue on all emails? Do the links have `href` attribute?

**Comment by e-t-l** [comment] 2020-03-24 02:37
Thanks for your help @markstos and @andy-portmen. Reverse mode seems to mostly work. The only issues with it now are that when I click a link in an email, it opens in two identical tabs in FF. And, occasionally when I click things in the Gmail sidebar like "Drafts" and "Trash," it opens those in FF tabs.

**Comment by e-t-l** [comment] 2020-04-23 20:19
I solved the duplicate tab issue: I didn't realize that when Reverse Mode is enabled, I should disable "Open with Keyboard-Mouse-Click Combinations" to prevent the request from being sent twice when links are clicked. 
I will check whether this also solves the second issue, where Gmail sidebar items are also sent to FF. Currently this second issue happens sporadically, and is typically resolved with a page refresh.

**Closed** 2020-11-29 11:11 UTC

**Comment by mcberta2** [comment] 2020-12-19 10:35
What is "reverse mode"? Where can I find the option?
Thanks
